// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzlTNnN-HsQhsnND8qK-ffRw76M4z_Lk',
    appId: '1:277758340353:web:8dea00447feb5325a8ff00',
    messagingSenderId: '277758340353',
    projectId: 'flutter-crud-application-cad65',
    authDomain: 'flutter-crud-application-cad65.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-cad65-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-cad65.firebasestorage.app',
    measurementId: 'G-8WYPXV4V6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGI-MO7LuqBLlhyHfMzlSaXsqhbXXPto',
    appId: '1:277758340353:android:82f9959c2f787811a8ff00',
    messagingSenderId: '277758340353',
    projectId: 'flutter-crud-application-cad65',
    databaseURL: 'https://flutter-crud-application-cad65-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-cad65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbfOgtsYc9o_k0o1VfOPgGHDB3B82BWE',
    appId: '1:277758340353:ios:99853f9925fc39d0a8ff00',
    messagingSenderId: '277758340353',
    projectId: 'flutter-crud-application-cad65',
    databaseURL: 'https://flutter-crud-application-cad65-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-cad65.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbfOgtsYc9o_k0o1VfOPgGHDB3B82BWE',
    appId: '1:277758340353:ios:99853f9925fc39d0a8ff00',
    messagingSenderId: '277758340353',
    projectId: 'flutter-crud-application-cad65',
    databaseURL: 'https://flutter-crud-application-cad65-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-cad65.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKzlTNnN-HsQhsnND8qK-ffRw76M4z_Lk',
    appId: '1:277758340353:web:0aecbfc3df0295bca8ff00',
    messagingSenderId: '277758340353',
    projectId: 'flutter-crud-application-cad65',
    authDomain: 'flutter-crud-application-cad65.firebaseapp.com',
    databaseURL: 'https://flutter-crud-application-cad65-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-application-cad65.firebasestorage.app',
    measurementId: 'G-D6JPRP0NJ6',
  );
}
